---
title: "bipartite_networks"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bipartite_newtorks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(sbmR)
library(dplyr)
library(tidyr)
library(ggplot2)

```


Start with the package included pollinators network.

```{r load-data}
clements_pollinators %>% head()

bind_rows(
  count(clements_pollinators, pollinator) %>% 
    transmute(id = pollinator, degree = n, type = "pollinator"),
  count(clements_pollinators, flower) %>% 
    transmute(id = flower, degree = n, type = "flower")
) %>% 
  ggplot(aes(x = degree)) +
  geom_histogram(binwidth = 1, color = 'white') +
  facet_grid(rows = "type", scales = "free_y") +
  labs(title = "Degree distributions for flower and pollinator nodes",
       subtitle = "Note different y-axis scales")
```

## Load into SBM

```{r}
pollinator_net <- new_sbm_network(edges = clements_pollinators,
                                  bipartite_edges = TRUE,
                                  edges_from_column = pollinator,
                                  edges_to_column = flower,
                                  random_seed = 42)

pollinator_net
```

## Visualize it

```{r}
visualize_network(pollinator_net, node_color_col = 'type', node_shape_col = 'none')
```



## Run agglomerative merging to find initial MCMC State

```{r}
pollinator_net <- pollinator_net %>% 
  collapse_blocks(desired_num_blocks = 4,
                  num_mcmc_sweeps = 5,
                  sigma = 1.1)
```


```{r}
visualize_collapse_results(pollinator_net, heuristic = "delta_ratio")
```
So we have a very clear peak. Let's select it as our starting position. 

```{r}
pollinator_net <- pollinator_net %>% 
  choose_best_collapse_state(heuristic = "delta_ratio", verbose = TRUE)
```


Let's visualize this result on the network layout

```{r}
pollinator_net %>% 
  visualize_network(node_shape_col = 'block', node_color_col = 'type')
```






